//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouchbaseConsole
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Post
    {
        public System.Guid PostId { get; set; }
        public string cuntcode { get; set; }
        public string cblgcode { get; set; }
        public string cestcode { get; set; }
        public string bigestcode { get; set; }
        public int RegionId { get; set; }
        public int GScopeId { get; set; }
        public string DisplayEstName { get; set; }
        public string DisplayAddress { get; set; }
        public System.DateTime OpDate { get; set; }
        public string PropertyRight { get; set; }
        public int PropertyTypeId { get; set; }
        public string PropertyType { get; set; }
        public int Floor { get; set; }
        public int FloorTotal { get; set; }
        public string FloorDisplay { get; set; }
        public double GArea { get; set; }
        public double NArea { get; set; }
        public int RoomCnt { get; set; }
        public int HallCnt { get; set; }
        public int ToiletCnt { get; set; }
        public int BalconyCnt { get; set; }
        public int KitchenCnt { get; set; }
        public string Direction { get; set; }
        public string Fitment { get; set; }
        public string PostType { get; set; }
        public double SellPrice { get; set; }
        public double UnitSellPrice { get; set; }
        public double RentalPrice { get; set; }
        public bool WithLease { get; set; }
        public double WithLeaseRental { get; set; }
        public System.DateTime WithLeaseExpired { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string VisitTime { get; set; }
        public string DefaultImage { get; set; }
        public string RemarkNo { get; set; }
        public bool IsFollow { get; set; }
        public bool IsSole { get; set; }
        public System.DateTime SoleExpired { get; set; }
        public int PostTag { get; set; }
        public string StaffNo { get; set; }
        public bool IsOnline { get; set; }
        public int PostStatus { get; set; }
        public bool RotatedIn { get; set; }
        public double PostScore { get; set; }
        public double AgentScore { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string AdsNo { get; set; }
        public string PostTagComment { get; set; }
        public string BuildingType { get; set; }
        public string PropStructure { get; set; }
        public string PlainDescription { get; set; }
        public string CestKeywords { get; set; }
    }
}
